name: Actions
on: push
defaults:
  runs-on: ubuntu-latest
  if: "!contains(github.event.head_commit.message, 'BOT:')"
jobs:
  test:
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.test.yaml up --build --exit-code-from test