version: "3.6"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - gitserver
  gitserver:
    build: ./git/test
    ports:
      - "22:22"
networks:
  default:
    driver: bridge
    internal: true
